--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "HR"."EMPLOYEE" 
   (	"ID" NUMBER(10,0), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"QUALIFICATION" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(250 BYTE), 
	"MOBILE" NUMBER(15,0), 
	"SALARY" NUMBER(20,2), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DATE_OF_JOINING" DATE, 
	"PAN" NUMBER(10,0), 
	"AADHAR" NUMBER(12,0), 
	"BANK_ACC" NUMBER(10,0), 
	"DESIGNATION" VARCHAR2(100 BYTE), 
	"MARITAL_STATUS" VARCHAR2(100 BYTE), 
	"DEPARTMENT_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.EMPLOYEE
SET DEFINE OFF;
Insert into HR.EMPLOYEE (ID,PASSWORD,GENDER,DATE_OF_BIRTH,QUALIFICATION,ADDRESS,MOBILE,SALARY,EMAIL,DATE_OF_JOINING,PAN,AADHAR,BANK_ACC,DESIGNATION,MARITAL_STATUS,DEPARTMENT_ID,NAME) values (1007

--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_BUG_TEAM
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_BUG_TEAM" 
   (	"ID" NUMBER(10,0), 
	"MEMBER_ID" NUMBER(10,0), 
	"LEADER" NUMBER(10,0), 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" NUMBER(10,0), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"TEAM_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_BUG_TEAM
SET DEFINE OFF;
Insert into HR.TRN_BUG_TEAM (ID,MEMBER_ID,LEADER,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,TEAM_ID) values (1,1001,1006,109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1);
Insert into HR.TRN_BUG_TEAM (ID,MEMBER_ID,LEADER,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,TEAM_ID) values (2,1002,1006,109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1);
Insert into HR.TRN_BUG_TEAM (ID,MEMBER_ID,LEADER,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,TEAM_ID) values (3,1003,1006,109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1);
Insert into HR.TRN_BUG_TEAM (ID,MEMBER_ID,LEADER,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,TEAM_ID) values (4,1003,1006,109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),2);
Insert into HR.TRN_BUG_TEAM (ID,MEMBER_ID,LEADER,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,TEAM_ID) values (5,1005,1006,109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),2);
Insert into HR.TRN_BUG_TEAM (ID,MEMBER_ID,LEADER,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,TEAM_ID) values (7,1001,1006,109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),2);
--------------------------------------------------------
--  DDL for Index PK_BUG_TEAM_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PK_BUG_TEAM_ID" ON "HR"."TRN_BUG_TEAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_TEAM
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_TEAM" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" NUMBER(10,0), 
	"MODIFIED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_TEAM
SET DEFINE OFF;
Insert into HR.TRN_TEAM (ID,NAME,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (3--------------------------------------------------------


--  Constraints for Table TRN_BUG_TEAM
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_BUG_TEAM" ADD CONSTRAINT "PK_BUG_TEAM_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_BUG_TEAM" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_BUG_TEAM" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_BUG_TEAM" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_BUG_TEAM" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_BUG_TEAM" MODIFY ("TEAM_ID" NOT NULL ENABLE);
 

CREATE TABLE "HR"."TRN_PROJECT" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ASSIGN_TO" NUMBER(10,0), 
	"CLIENT_NAME" VARCHAR2(100 BYTE), 
	"CLIENT_ADDRESS" VARCHAR2(250 BYTE), 
	"CLIENT_MOBILE" NUMBER(15,0), 
	"CLIENT_EMAIL" VARCHAR2(50 BYTE), 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" NUMBER(10,0), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"STATUS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_PROJECT
SET DEFINE OFF;
Insert into HR.TRN_PROJECT (ID,NAME,DESCRIPTION,START_DATE,END_DATE,ASSIGN_TO,CLIENT_NAME,CLIENT_ADDRESS,CLIENT_MOBILE,CLIENT_EMAIL,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS) values (53

--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_BUG
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_BUG" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"PROJECT_ID" NUMBER(10,0), 
	"RAISEDDATE" DATE, 
	"RAISED_BY" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"BUG_TYPE" VARCHAR2(100 BYTE), 
	"BUG_PRIORITY" VARCHAR2(50 BYTE), 
	"RAISED_TO" NUMBER(10,0), 
	"BUG_STATUS" VARCHAR2(20 BYTE), 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" NUMBER(10,0), 
	"MODIFIED_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_BUG
SET DEFINE OFF;
Insert into HR.TRN_BUG (ID,NAME,PROJECT_ID,RAISEDDATE,RAISED_BY,DESCRIPTION,BUG_TYPE,BUG_PRIORITY,RAISED_TO,BUG_STATUS,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (36

--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_SOLUTION
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_SOLUTION" 
   (	"ID" NUMBER(10,0), 
	"BUG_ID" NUMBER(10,0), 
	"SOLVED_BY" NUMBER(10,0), 
	"SOLVED_DATE" DATE, 
	"CREATED_BY" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" NUMBER(10,0), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"ROOTCAUSE" VARCHAR2(100 BYTE), 
	"CORRECTIVENESS" VARCHAR2(100 BYTE), 
	"SUMMARY" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_SOLUTION
SET DEFINE OFF;
Insert into HR.TRN_SOLUTION (ID,BUG_ID,SOLVED_BY,SOLVED_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,ROOTCAUSE,CORRECTIVENESS,SUMMARY) values (18,36,1003,to_date('25-05-19','DD-MM-RR'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),109,to_timestamp('09-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM')
